// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHNU9G8vGttR4Z1Ocn6coI7Wtm2MAo6rI',
    appId: '1:65975142578:android:98fa18fa8956021900a1ab',
    messagingSenderId: '65975142578',
    projectId: 'fandom-verse-pocket-2026',
    storageBucket: 'fandom-verse-pocket-2026.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2ozkRmqQQ9XywgCQlgofxtuDfZp2H3xk',
    appId: '1:65975142578:web:c4340b07e2d840dc00a1ab',
    messagingSenderId: '65975142578',
    projectId: 'fandom-verse-pocket-2026',
    authDomain: 'fandom-verse-pocket-2026.firebaseapp.com',
    storageBucket: 'fandom-verse-pocket-2026.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2ozkRmqQQ9XywgCQlgofxtuDfZp2H3xk',
    appId: '1:65975142578:web:91173f2258a18e4d00a1ab',
    messagingSenderId: '65975142578',
    projectId: 'fandom-verse-pocket-2026',
    authDomain: 'fandom-verse-pocket-2026.firebaseapp.com',
    storageBucket: 'fandom-verse-pocket-2026.firebasestorage.app',
  );

}